language: cpp
compiler: gcc

matrix:
 include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=59
  - os: osx
    compiler: clang
    env:
     - QT_BASE=59

cache:
  directories:
    - Qt

addons:
  apt:
    packages:
      - libbz2-dev
      - libfftw3-dev
      - libfishsound1-dev
      - libid3tag0-dev
      - liblo-dev
      - liblrdf0-dev
      - libmad0-dev
      - liboggz2-dev
      - libpulse-dev
      - libsamplerate-dev
      - libsndfile-dev
      - libsord-dev
      - libxml2-utils
      - portaudio19-dev
      - raptor-utils
      - librubberband-dev
      - mlton
      - swig

before_install:
  - if [[ "$QT_BASE" = "59" && "$TRAVIS_OS_NAME" = "linux" ]]; then
      sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
      sudo apt-get update -qq;
    else
      brew update;
    fi
  # Install PocketSphinx
  - wget https://sourceforge.net/projects/cmusphinx/files/sphinxbase/5prealpha/sphinxbase-5prealpha.tar.gz
  - tar -xzvf sphinxbase-5prealpha.tar.gz && mv sphinxbase-5prealpha sphinxbase
  - cd sphinxbase && ./configure && make && sudo make install && cd ..
  - wget https://sourceforge.net/projects/cmusphinx/files/pocketsphinx/5prealpha/pocketsphinx-5prealpha.tar.gz
  - tar -xzvf pocketsphinx-5prealpha.tar.gz && mv pocketsphinx-5prealpha pocketsphinx
  - cd pocketsphinx && ./configure && make clean all && sudo make install && cd ..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

install:
  # Needed for a C++14 compiler
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get install -qq g++-5;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90;
    fi
  #
  - if [ "$QT_BASE" = "59" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -qq qt59base ;
        sudo apt-get install -qq qt59charts-no-lgpl ;
        sudo apt-get install -qq qt59imageformats ;
        sudo apt-get install -qq qt59multimedia ;
        sudo apt-get install -qq qt59svg ;
        sudo apt-get install -qq qt59webengine ;
        source /opt/qt59/bin/qt59-env.sh;
      else
        brew install qt5;
        brew link --force qt5;
        export HOMEBREW_QT5_VERSION=$(brew list --versions qt5 | rev | cut -d' ' -f1 | rev);
        ln -s /usr/local/Cellar/qt5/$HOMEBREW_QT5_VERSION/mkspecs /usr/local/mkspecs;
      fi
    fi

script:
  # Check versions
  - g++ -v;
  - qmake -v;
  # Create build directory
  - mkdir ./build && cd ./build
  # Build Praaline
  - qmake ../Praaline.pro CONFIG+=release;
  - make;

notifications:
  email: false

